config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :customers

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #root "customers#index"
  #get customers_path
  get '/customers', to: 'customers#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders, dependent: :destroy

    validates :first_name, presence: true, format: { with: /\A[a-z\-' ]+\z/i }
    validates :last_name, presence: true, format: { with: /\A[a-z\-' ]+\z/i }
    validates :phone, presence: true
    validates :phone, numericality: { only_integer: true }
    validates :phone, length: { is: 10 }
    validates :email, presence: true, email: true
   
    def full_name
      "#{first_name} #{last_name}"
    end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  validates :product_name, presence: true
  validates :product_count, presence: true
  validates :customer, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
   #  @customer = Customer.new(customer_params)

   # respond_to do |format|
   #   if @customer.save
   #     format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
   #     format.json { render :show, status: :created, location: @customer }
   #   else
   #     format.html { render :new, status: :unprocessable_entity }
   #    format.json { render json: @customer.errors, status: :unprocessable_entity }
   #   end
   # end
   @customer = Customer.new(customer_params)
   #@customer.save
    if @customer.save
      flash[notice] = "The customer record was created successfully."
      redirect_to @customer
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
   # respond_to do |format|
   #   if @customer.update(customer_params)
   #     format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
   #     format.json { render :show, status: :ok, location: @customer }
   #  else
   #     format.html { render :edit, status: :unprocessable_entity }
   #     format.json { render json: @customer.errors, status: :unprocessable_entity }
   #   end
   # end
   if @customer.update(customer_params)
    flash.notice = "The customer record was updated successfully."
    redirect_to @customer
  else
    render :edit, status: :unprocessable_entity
  end

  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    flash.notice = "The customer record was successfully deleted."
    rescue ActiveRecord::InvalidForeignKey
    flash.notice = "That customer record could not be deleted, because the customer has orders."

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      #  <% debugger %>
      @customer = Customer.find(params[:id])

    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone, :email)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to customers_path
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_order, only: [:show, :edit, :update, :destroy]
  
    # GET /orders
    def index
      @orders = Order.all
    end
  
    # GET /orders/:id
    def show
      # @order is already set by the before_action :set_order
    end
  
    # GET /orders/new
    def new
      @order = Order.new
    end
  
    # GET /orders/:id/edit
    def edit
      # @order is already set by the before_action :set_order
      @order = Order.find(params[:id])
    end
  
    # POST /orders
    def create
      @order = Order.new(order_params)
  
      if @order.save
        redirect_to @order, notice: 'Order was successfully created.'
      else
        render :new
      end
    end
  
    # PATCH/PUT /orders/:id
    def update
      if @order.update(order_params)
        redirect_to @order, notice: 'Order was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /orders/:id
    def destroy
      @order.destroy
      redirect_to orders_url, notice: 'Order was successfully deleted.'
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def order_params
     # params.require(:order).permit(:customer_id, :product_id, :quantity, :total_price, :status)
      params.require(:order).permit(:product_name, :product_count, :customer_id)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
 
<tr>
  <td><%= customer.full_name %></td>
  <td><%= customer.email %></td>
  <td><%= customer.phone %></td>
  <td><%= customer.orders.count %></td>
  <td>
    <%= link_to "Show", customer_path(customer), class: "btn btn-primary" %> |
    <%= link_to "Edit", edit_customer_path(customer), class: "btn btn-primary" %> |
    <%= link_to "Delete", customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
  </td>
</tr>

app/views/customers/_deleteModal.html.erb
<div class="modal" id="<%= "myModal-#{customer.id}" %>">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Are you sure?</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
       <p>Are you sure you want to delete the customer and order records for <%= customer.full_name %>?
           That customer has <%= customer.orders.count.to_s %> orders.  If there are any orders for this
           customer, those orders will be deleted too! </p>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
      <%= button_to("Delete", "/customers/customerAndOrders/#{customer.id}", method: :delete, class: "btn btn-danger", 
      data: { "bs-dismiss" => "modal" })  %>
<button type="button", class="btn btn-primary" data-bs-dismiss="modal">Cancel</button>         
      </div>

    </div>
  </div>
</div>

app/views/customers/_form.html.erb
<%= form_with(model: @customer, local: true) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this order from being saved:</h2>
      <ul>
        <% @customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<h1>Customers</h1>

<div id="customers">
<table>
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Orders</th>
  </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.full_name %></td>
        <td><%= customer.orders.count %></td>
        <td><%= link_to 'Show', customer, :class => "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer), :class => "btn btn-primary" %></td>
        <td><%= button_to "Delete Record", customer, method: :delete, data: { turbo_confirm: "Are you sure?"}, :class => "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= link_to "New customer", new_customer_path, :class => "btn btn-primary" %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/show.html.erb
<h1><%= @customer.full_name %> Details</h1>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @customer.phone %>
</p>

<h2>Orders</h2>
<% if @customer.orders.any? %>
  <table>
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Product Count</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @customer.orders.each do |order| %>
        <tr>
          <td><%= order.product_name %></td>
          <td><%= order.product_count %></td>
          <td>
            <%= link_to 'Show', order_path(order) %> |
            <%= link_to 'Edit', edit_order_path(order) %> |
            <%= link_to 'Destroy', order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No orders found for this customer.</p>
<% end %>

<%= link_to 'Back to Customers', customers_path %>

app/views/layouts/_hero.html.erb
<div class="my-2 bg-body-tertiary rounded-3 banner-background">
    <div class="p-5 rounded-3">
        <div class="container-fluid py-5">
            <div class="text-white">
                <div>
                    <h1 class="display-5 text-white">Welcome to <strong class="fw-bold">Furni</h1>
                </div>
                <p class="col-md-8 fs-4">How about doing a little work today?</p>
                <div class="d-flex align-items-center">
                    <%= link_to "Create new customer", new_customer_path, class:"btn btn-primary" %>
                    <p class="mx-2 mb-0">or</p>
                    <%= link_to "Create new order", new_order_path, class:"btn btn-primary" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Furni</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/customers">Customers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/orders">Orders</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R7Additional</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <div class="container-fluid">
  <div class="mt-4 p-5 bg-primary text-white rounded banner-background">
    <h1>Customers and Orders</h1>
    <p>This is a sample application that associates orders with customers.</p>
  </div>
  <% if flash[:alert].present? %>
    <p class="alert alert-danger"><%= flash[:alert] %></p>
  <% end %>
  <% if flash[:notice].present? %>
    <p class="alert alert-success"><%= flash[:notice] %></p>
  <% end %>
  <nav class="navbar navbar-expand-sm bg-light">

  <div class="container-fluid">
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
      <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown">
      Customers <%= icon('fa-solid', 'user')%>
    </button>
        <ul class="dropdown-menu">
          <li class="dropdown-item">
            <a class="nav-link" href=<%= customers_path %>>Customer List</a>
          </li>
          <li class="dropdown-item">
          <a class="nav-link" href=<%= new_customer_path%>>New Customer</a>
        </li>
        </ul>
      </li>
      <li class="nav-item">
      <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown">
      Orders <%= icon('fa-solid', 'boxes-packing')%>
    </button>
        <ul class="dropdown-menu">
          <li class="dropdown-item">
            <a class="nav-link" href=<%= orders_path %>>Order List</a>
          </li>
          <li class="dropdown-item">
          <a class="nav-link" href=<%= new_order_path %>>New Order</a>
        </li>
        </ul>
      </li>
    </ul>
  </div>

</nav>
      <%= yield %>
  </div>
  </body>
</html>

app/views/orders/_deleteModal.html.erb
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Are you sure?</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <!-- Modal body -->
      <div class="modal-body">
        <p>Are you sure you want to delete the order from <span id="customerName"></span>
            for <span id="productCount"></span>
            of our <span id="productName"></span> product?
        </p>
      </div>
      <!-- Modal footer -->
      <div class="modal-footer">
        <%= button_to("Delete", nil, method: :delete, class: "btn btn-danger",
          data: { "bs-dismiss" => "modal" }, form: {id: "doDelete"})  %>
        <button type="button", class="btn btn-primary" data-bs-dismiss="modal">Cancel
        </button>       
      </div>
    </div>
  </div>
</div>
<script>
document.addEventListener("DOMContentLoaded", () => {
  const myModal = document.getElementById("myModal");
  myModal.addEventListener("show.bs.modal", (e) => {
    const triggerButton = e.relatedTarget;
    const customerName = document.getElementById("customerName");
    const productName = document.getElementById("productName");
    const productCount = document.getElementById("productCount");
    const doDelete = document.getElementById("doDelete");
    
    customerName.textContent = triggerButton.getAttribute("data-customer");
    productName.textContent = triggerButton.getAttribute("data-productname");
    productCount.textContent = triggerButton.getAttribute("data-productcount");
    
    doDelete.action = `/orders/${triggerButton.getAttribute("data-id")}`;
  });
});
</script>

app/views/orders/_form.html.erb
<%= form_with(model: @order, local: true) do |f| %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
        <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :product_name %>
      <%= f.text_field :product_name %>
    </div>
  
    <div class="field">
      <%= f.label :product_count %>
      <%= f.number_field :product_count %>
    </div>
  
    <div class="field">
      <%= f.label :customer_id %>
      <%= f.collection_select :customer_id, Customer.all, :id, :full_name, include_blank: true %>
    </div>
  
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <div class="card-header">
    <p>
      <strong>Product:</strong>
      <%= order.product_name %>
    </p>
  </div>
  <div class="card-body">
    <p>
      <strong>Customer:</strong>
      <%= order.customer.full_name %>
    </p>
    <p>
      <strong>Quantity</strong>
      <%= order.product_count %>
    </p>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back to Orders', orders_path %>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders" class="container-fluid row">
  <% @orders.each do |order| %>
    <div class="card border border-2 border-success p-1 mt-3" style="width: 18rem;">
      <%= render order %>
      <div class="card-footer">
        <p>
          <%= link_to "Show this order", order, :class => "btn btn-primary" %>
          <%= link_to 'Edit order', edit_order_path(order), :class => "btn btn-primary" %>
          <%= button_to "Delete order", order, method: :delete, data: { turbo_confirm: "Are you sure?"}, :class => "btn btn-primary" %>
        </p>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New order", new_order_path, :class => "btn btn-primary" %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back to Orders', orders_path %>

app/views/orders/show.html.erb
<h1>Order #<%= @order.id %> Details</h1>

<div class="card border border-2 border-success p-3 mt-3" style="width: 18rem;">
  <div class="card-header">
    <h4>Order Details</h4>
  </div>
  <div class="card-body">
    <p><strong>Product Name:</strong> <%= @order.product_name %></p>
    <p><strong>Product Count:</strong> <%= @order.product_count %></p>
    <p><strong>Customer:</strong> <%= @order.customer.full_name %></p>
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_order_path(@order), class: 'btn btn-primary' %> |
    <%= link_to 'Back', orders_path, class: 'btn btn-secondary' %> |
    <%= link_to 'Destroy', order_path(@order), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </div>
</div>